style:
  MagicNumber:
    excludes: [
      '**/type/**',
      '**/test/**'
    ]
complexity:
  LongMethod:
    allowedLines: 80
  TooManyFunctions:
    allowedFunctionsPerFile: 21
    allowedFunctionsPerClass: 21
formatting:
  ImportOrdering:
    layout: '*,java.**,javax.**,kotlin.**,kotlinx.**,^'